### ISSUE TITLE
Support for Mineralogy Mod? - 1.10.2

### ISSUE THREAD

**Issue by WenXin20** [WhiskyTangoFawks/Expedition#10]
This mod changes the stone that spawns, so things like the stalactites and stalagmites don't spawn.

**Comment by WhiskyTangoFawks** [comment]
Stalactites and all decorative blocks for mods that add stone types are supported in beta13, however the stone blocks need to be added to the config to be recognised (WTFCore.cfg).  It can't detect them automatically, but you can add them now.

**Comment by WenXin20** [comment]
How do I format the modded blocks in the config? I can't figure out how without it causing an error and crashing.

**Comment by WhiskyTangoFawks** [comment]
if it's crashing, it's because you have the block registry name wrong.  Turn on the name getter (in the core config), and go into creative mode and place the block you want in the world- it'll spit out the block registry name and metadata to chat.  Then, just put that in, formatted how the existing ones are, ModID:BlockName@Metadata,  Note it is case sensitive.  If there's a stone and cobblestone pair, put in both, if there's no cobblestone for the stone, just put the stone in twice (see the vanilla stones as an example).

**Comment by WenXin20** [comment]
Thanks, is there a way for it to include all metadata in one line, like making it work for all stained clay variants, or do I need to list each color individually?

**Comment by WhiskyTangoFawks** [comment]
Each need to be done individually.

**Comment by WenXin20** [comment]
ok, thanks
