### ISSUE TITLE
Runaway worldgen

### ISSUE THREAD

**Issue by ruyanve** [WhiskyTangoFawks/Expedition#113]
Hey mate,

Mezz has written a nice post on reddit about worldgen problems. You seem to have solved most of the lag issues, but in case you haven't seen it, here's the link:
https://www.reddit.com/r/feedthebeast/comments/5x0twz/investigating_extreme_worldgen_lag/

**Comment by WhiskyTangoFawks** [comment]
Yeah, because what I'm doing is so complex (mainly because it's large, and in every chunk), it adds another level of complexity on top of everything, of having to make sure that adjacent chunks are also generated before I do anything to a chunk.

But yes, I do have most of the issues solved now.  Definitely an interesting read
