### ISSUE TITLE
1.10.2 Worldgen Change?

### ISSUE THREAD

**Issue by Darkosto** [WhiskyTangoFawks/Expedition#122]
Hey Whiskey,

Quick question for you:

I use Quark to generate massive caves in the world for a unique style map. When I updated to WTF Expedition Beta 5 and then to Beta 6 the Quark caves did not generate at all. I backported to Beta1 and was able to retain the large caves. Was there a big change to your worldgen that would nullify Quark's worldgen in 5 and 6? If so, will this be a permanent change or can there be something to disable it? I would hate to not stay current with your latest updates so I can keep up with bugfixes/etc.

Thank you!
Darkosto

**Comment by WhiskyTangoFawks** [comment]
yes, there was a change- in order to monitor where I've generated and where I've not, I replaced the cave structure generation with a class that calls the vanilla cave structures (I needed a hook at that point in world generation, and there's no forge event that has the right timing).

I can, in theory, fix this by wrapping the existing cave structure class, instead of just assuming it's vanilla.  That should retain the modified cave generation.  I'll try and get a fix out for testing this weekend.

**Comment by Darkosto** [comment]
That would be great if you were able to! I can test anything out for you if needed. Just let me know if you need anything from me and I'll help out. Thanks again! :)

**Comment by WhiskyTangoFawks** [comment]
new beta's out, should fix the issue.

**Comment by Darkosto** [comment]
Thank you!

**Comment by Darkosto** [comment]
Is there a particular config option for this? The generation still seems to be experiencing the same issue with Quark not generating.

**Comment by Darkosto** [comment]
This issue is not resolved in these versions, is this something that can be reopened please?

Also, did you archive the version 1.5Beta1 on Curse? This is the only version that works for me and my custom worldgen on a public pack that I've released.

Thank you!

**Comment by WhiskyTangoFawks** [comment]
I'll put up another version with a tweak that might solve the issue, but if not, then the problem is the sandstone replacer I added after version 1.5beta1 being incompatible with another mod you're running.  Just turn it off in the cave biomes config.  (make sure you're on the new version, I found a bug in the earlier release where that config option wasn't doing anything, I've fixed it and the new version will have it working).

**Comment by WesCook** [comment]
Just a heads up Whisky, I'd suggest against archiving older releases unless there's a serious bug.  Often times packs need specific versions, and removing the download makes it impossible to then join those servers.

It also makes it trickier to follow things like changelogs, as those are tied to file downloads.

**Comment by Darkosto** [comment]
Hey @WhiskyTangoFawks I've updated this mod and added the newer gameplay mod, everything seems to be working perfectly! Thank you very much for you time and patience. You're work has been very much appreciated!

Take care!
Darkosto
