### ISSUE TITLE
Is there a complete list of biome types?

### ISSUE THREAD

**Issue by DanteTorn** [WhiskyTangoFawks/Expedition#155]
I'm modifying the Homestead modpack currently and I'm changing some of the oregen, such as limiting redstone to only spawn in deserts. I noticed that some of the biome types are unusual such as "sandy" and it'd be best if I knew what the full list was so I could make better use of it as well as understanding what types apply to what biomes. Is there a full list of biome types and what they apply to somewhere?

I've been trying to look everywhere for documentation or files but haven't found any. I emailed WesCook (creator of Homestead modpack) and they did say that there probably wouldn't be much documentation on it.

**Comment by WhiskyTangoFawks** [comment]
Biome type tags are supplied by Forge itself. You can find the list of tags here https://mcreator.net/wiki/minecraft-forge-biome-dictionary-types-list, I wasnt able to find an easy list of which tags apply to which of the vanilla biomes, you would probably need to dig through the code to find the initialization (which is easy to do, if you have some basic experience reading java). The type tags are descriptors that are added to the vanilla biomes by forge (and mods tag their own biomes). So, instead of using the vanilla biome desert, my mod uses the type tags sandy, for biomes which forge thinks are "sandy". Same for "forest", "wet", etc.

There might be some information in my old forum threads, if they are archived somewhere, or in curseforge download page. Look for something about setting up the config files. Sorry I can't be more help, its been years since I looked at this mod, I'm honestly suprised someone is still using it, but I'm glad you're enjoying it.
