### ISSUE TITLE
Custom Stalagmites Glitched Texture

### ISSUE THREAD

**Issue by WenXin20** [WhiskyTangoFawks/Expedition#18]
I added blocks to the stone sets config, but they just show glitched textures in the game. I tried it with Netherrack and hardened clay. 
Forge 2092

**Comment by WhiskyTangoFawks** [comment]
That's because you have to generate blockstate jsons for them, as per the instructions in the forum thread on the update.

**Comment by WenXin20** [comment]
Ok

**Comment by WenXin20** [comment]
How do I get modded textures to work for the models?
I tried this: assets/chisel/textures/blocks/basalt/extra/raw
& this: chisel/textures/blocks/basalt/extra/raw

**Comment by WhiskyTangoFawks** [comment]
there are blockstate json files .  Open up the .jar for expedition (rename to .zip, and just open it), and go into the assets.  Copy stone0decoanim.json, stone0decostatic.json, stone0speleothem.json, and stone0speleothemfrozen.json.

Rename them with the block registry name (without the modID) and metadata instead of stone0.  Then, open each file (I recommend using notepad++, or other advanced text editor, but anything should work), and replace "stone" with name of the texture file (and here, if it's not a vanilla block, you need to include the modid- so something like "chisel:basalt").  Those files

**Comment by WenXin20** [comment]
Thanks for the help

**Comment by WenXin20** [comment]
Is it possible for it to work with the chisel or biomes o plenty mod?
For chisel, I'm trying to add basalt, limestone, and marble, but the png's are all named raw.png, just in separate folders.
For biomesoplenty, the limestone id is biomesoplenty:stone@0, so how would I make a file without it replacing normal stone?

**Comment by WhiskyTangoFawks** [comment]
For the blockstate jsons, you will need the resource path for texture, e.g. something like chisel:limestone/raw.png

For biomes o plenty, if they're using the exact same registry name as vanilla, then it won't work currently.  I can add something that'll change the default name if that name is already registered, but it's not a high priority.

**Comment by WenXin20** [comment]
Ok, thanks

**Comment by WenXin20** [comment]
Putting chisel:limestone/extra/raw.png didn't seem to work.
For quark it only provides a JSON for basalt, and it doesn't seem to work to put quark:blocks/basalt.json

**Comment by WhiskyTangoFawks** [comment]
Check whether you're getting a model error, or a texture error.  You can do that by looking in the client log for the error messages about loading textures and models, or in game, if the block has the stalactite model, but the null texture, or whether it's just the basic block model.  Have a read of the error messages, and see if anything explains what's going on.

If it's a model error, then check that the blockstate json is correctly named against the block- they should be the same.  If it's a texture error, and you're able to load the model but not find the texture, then the problem is that you've not gotten the path for the texture right.  Look in the file structure for the mod, and see where they store it.

You need to refer to the texture file, so look for basalt.png (and don't include the extension).  Don't reference another json file, you want the texture file.

**Comment by WenXin20** [comment]
Ok, thanks for all the help.
