### ISSUE TITLE
Torches don't have vanilla behavior (cosmetic)

### ISSUE THREAD

**Issue by Cat-McCatface** [WhiskyTangoFawks/Expedition#2]
When I explicitly disabled gameplay tweaks in wtfcore.cfg and separately disabled finiate torches in the other config file vanilla torches placed in multiplayer environment still behave like "right click to light." The server itself doesn't support forge mods so it shouldn't be allowing me to place the wtfcore items in environment.

screenshot (part of one) [http://i.imgur.com/Mo9EEM2.jpg]

settings are:
B:"Set to false to disable all gameplay tweaks for a vanilla gameplay experience.  This override ALL options set inside WTFGameplay.cfg"=false
I:"0 = disable finite torches, 1 = Relight torches with a right click, 2= relight torches with a flint and steel only"=0
I:"Chance in 100 per block tick (avg every 45 seconds) that an unattended torch will go out, 0 disables torches going out, -1 prevents torch replacement entirely"=0

forge: 2052
WTF-Expedition_1.10.2_Beta10

**Comment by WhiskyTangoFawks** [comment]
Delete your config and regenate it, there's some trash in there from the earlier beta versions that is no longer functional.

The torches are aliased, they replace vanilla blocks.  Because you haven't turned off replacement, it's aliasing on the client still.  

Set I:"Chance in 100 per block tick (avg every 45 seconds) that an unattended torch will go out, 0 disables torches going out, -1 prevents torch replacement entirely"= 

to -1, instead of zero.

The fact that gameplay tweaks are completely disabled and it's still doing anything was a bug.  It's fixed for the next release.
