### ISSUE TITLE
Crash - During World Generation

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [WhiskyTangoFawks/Expedition#22]
Issue
https://gist.github.com/DPxKnightxZero/237043df0faca7ef0424b976fff558e3

Already informed Chisels and Bits creator - 

Crashlog
https://gist.github.com/DPxKnightxZero/7da78feef2d08f1578df8dc237b7cbd5

**Comment by WhiskyTangoFawks** [comment]
Looks like maybe chisels and bits is calling the render method for my block.  I'd guess there's a derivative block, that because it lacks the property, causes the crash, so I think the bug is in the chisels and bits code.  If I'm right,  it needs to call the render method with my block state, instead of the derivative block's state.

**Comment by P3rf3ctXZer0** [comment]
https://github.com/AlgorithmX2/Chisels-and-Bits/issues/216
