### ISSUE TITLE
[BUG] Wither spawning impossible with gravity for soulsand.

### ISSUE THREAD

**Issue by KoenHoogendoorn1994** [WhiskyTangoFawks/Expedition#57]
In the last version of the mod, making the wither structure is impossible due to soulsand being affected by gravity. Supporting the side soulsand pieces with cobblestone invalidates the structure. Temporarily fixed it by removing soulsand from the list in the config file, but I don't know why you'd ever want to enable it.

**Comment by WesCook** [comment]
Another workaround is building the structure sideways, as withers can be spawned horizontally.

**Comment by KoenHoogendoorn1994** [comment]
And so you learn something new every day :P I was completely unaware XD

**Comment by WhiskyTangoFawks** [comment]
You can also prevent falling by placing a fence block nearby (it can be a block or two away, not actually touching, and prevent it falling, depending on how you place it).

Hadn't thought about wither, just added soulsand to the falling list because it has sand in the title.  You're not wrong that it can be problematic, so I might remove it from the default list.  Players who want it can always add it back.
