### ISSUE TITLE
Missing Textures 1.10.2

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [WhiskyTangoFawks/Expedition#58]
1.10.2 latest version was missing many textures.

**Comment by darkphan** [comment]
You need to load the resource pack that gets generated

**Comment by P3rf3ctXZer0** [comment]
Since when?

**Comment by WhiskyTangoFawks** [comment]
Since the changleog told you to do it in the first 1.3 beta.

I've got someone helping me on code to auto-enable it, so you should eventually not need to, but for now, just make sure the that the WTFOres resourcepack is enabled.  I made the change so I could auto-generate blockstate files, allowing better customisation, and easier adding of custom ores.
