### ISSUE TITLE
Crash with ore generation

### ISSUE THREAD

**Issue by Biochao** [WhiskyTangoFawks/Expedition#75]
Occasionally when new chunks generate the game crashes. At first I thought TerrainControl/Biome Bundle was conflicting so I tried Biomes O Plenty. It still happened with BoP so I created a vanilla terrain world and it crashed while creating spawn. 
Here is that crash log. 
[crash-2017-01-08_18.53.03-server.txt](https://github.com/WhiskyTangoFawks/Expedition/files/700392/crash-2017-01-08_18.53.03-server.txt)

To me, reading the crash log looks like ores are trying to generate below y=0. If I have a negative y value set in the config I'm not seeing it.
Here is my oregen config: 
[WTFOresConfigV2.txt](https://github.com/WhiskyTangoFawks/Expedition/files/700394/WTFOresConfigV2.txt)

I'm using WTF-Expedition_1.10.2_v1.3.3

**Comment by WhiskyTangoFawks** [comment]
Not quite.  What's happening is that (maxHeight-minHeight) is less than 1.

I suspect that the problem is taiga:eezo_ore@0 #single.  Because world gen is scaled to height, in a chunk with an average height less than 32, 5% and 6% both round to exactly the same number, and a number minus itself = 0, which will crash when thrown into a random number generator as a bounds.  I'll add a catch in the next version to stop it crashing in case anyone else does this, but if you just change that to a larger range it should be fine.

**Comment by Biochao** [comment]
Ok, changing eezo_ore to 1-6% fixed that crash but it's still crashing when populating chunks...
Here's the full log:
[fml-client-latest.txt](https://github.com/WhiskyTangoFawks/Expedition/files/702684/fml-client-latest.txt)

**Comment by WhiskyTangoFawks** [comment]
As far as I can tell, my mod isn't responsible for that one.  Looks like maybe journey map?  Check that the mod is up to date, and that you're on the wrong version of forge.
Also, the crash log would be more helpful to you than the client in this instance, just a little easier to read.

**Comment by Biochao** [comment]
Sorry, it was something I had changed in Quarks config. Probably increasing the stone variations spawn sizes. Generating a new config fixed it.
One last question. When eezo ore generates in bedrock, will it generate less in mountainous biomes because the height percentages will be scaled up?

Thanks for the help.

**Comment by WhiskyTangoFawks** [comment]
Not familiar with that mod, and what you mean by generate in bedrock.

But, for instance, 5% of 200 is 10 blocks, and if you're set to 5-6 percent, you'll get that ore spawning in between 10-12 in an area with an average height of 200 (which is rare).  At sea level, 5-6 percent  is 3.2-3.8, which after rounded to integers, is 3 to 3 (which, incidentally, would crash the game on the current build).  If you're trying to mimic something spawning very, very low, I'd recommend setting it to 0-6 or so, and setting the generation rate at about twice as high as you would otherwise (because half the blocks there are actually going to be bedrock, and won't spawn- unless of course you're using bedrock as a background for the ore- which if you're not, is an interesting idea I kind of want to play around with now...).

**Comment by Biochao** [comment]
The [TAIGA](https://minecraft.curseforge.com/projects/taiga-tinkers-alloying-addon) mod adds a bunch of metals to Tinkers Construct. One of them, Eezo, is a bedrock ore. Normaly it would generate in y layers 1-5 with the rest of the bedrock.

Testing it in survival it looks like additional tweaking may be required as having bedrock as the background block means the ore is unbreakable in survival. If possible I may have to use [Harvest Level Tweaks](https://minecraft.curseforge.com/projects/harvest-tweaks) to make "wtfcore:dense_bedrock0eezo_ore0" harvestable. Although, then it would drop a bedrock block after the final variation, right?

**Comment by Biochao** [comment]
After a bit of testing, I had to set the very deep ores to 0-30% because Deep Oceans in my pack can go down to a Y-level of 8. Was crashing while flying over them with 0-10%.

**Comment by WhiskyTangoFawks** [comment]
I'll have the next version out with a fix for that bug in the next day or so hopefully.

I should theoretically be able to add a few simple config options to make bedrock a little more cooperative as an ore background, but that will take some tweaking.

**Comment by WhiskyTangoFawks** [comment]
new version's out

you should be able to set a small gen range without worrying about crashing now.  I've also added a language file writer, which should create english localised block names (based on the texture file names).
