### ISSUE TITLE
missing texture for dense_stone0ore5

### ISSUE THREAD

**Issue by cdfa** [WhiskyTangoFawks/Expedition#79]
Hi, i'm getting the purple/black texture for dense_stone0ore5 and all variants of undergoundbiomeconstruct. I have the WTFExpidition texture pack enabled. It is a terrain control world, but all ore generation from biome bundle is disabled.
Here are the relevant configs
[WTFStoneRegistry.txt](https://github.com/WhiskyTangoFawks/Expedition/files/717668/WTFStoneRegistry.txt)
[WTFOresConfigV2.txt](https://github.com/WhiskyTangoFawks/Expedition/files/717672/WTFOresConfigV2.txt)

**Comment by cdfa** [comment]
just regenerated the texture pack and noticed the overlays folder is empty. Can't be good...

**Comment by WhiskyTangoFawks** [comment]
I'm assuming that you're attempting to add some custom ore to my mod.  The overlays folder of the texture pack is empty because you've not put an ore overlay texture in for your custom ore.  And the block has a null texture, because it can't find the overlay texture, because you haven't supplied one.  I ship the mod with vanilla ore textures, and a couple others, but generally if you want to add custom ores you need to supply the overlays yourself- which is what the empty overlays folder it for.  The mod description has some more information on what you need to do (although I do need to update it a bit more since the overhaul), and if anything isn't clear on how to proceed feel free to ask.

**Comment by cdfa** [comment]
ah i see where i forgot to disable the use dense ore option now. Sorry! One thing that definitely could be improved is config debugging. I spent quite a while getting these configs to work, because the crash reports aren't very specific. At least telling me which ore config caused the error should be possible right?

**Comment by WhiskyTangoFawks** [comment]
All the crash reports should at least print out the string from the master config that's being processed.  And if that isn't enough, or if you're doing something more complex, the log files may be helpful though.

Also, as you're using UBC, just FYI I've got some bug fixed in the pipeline, next release should be out this weekend that will improve compatibility quite a bit.

**Comment by cdfa** [comment]
Ah nice, i noticed some ore being of the wrong stone type, but only saw it once or twice, so didn't think it was big enough of a problem to bring to your attention directly and that it would probably be fixed soon.
