### ISSUE TITLE
Incompatibility Issue - "Enhanced Visuals"

### ISSUE THREAD

**Issue by XvSkItZvX** [WhiskyTangoFawks/Expedition#98]
As I am unsure of the actual cause of the crash this issue will be duplicated on both Mod pages.

[Latest Error Report](http://pastebin.com/5L13i4RK ) - Can supply 4 others if needed.
Current [List of Mods](http://www.modlister.com/user/XvSkItZvX/%20Trouble%20Shooting%20Snapshot%20One)) in this package.
Enhanced Visuals Release: EnhancedVisuals v1.0.9 mc1.9-1.10.jar
"WTF's Expedition: CaveBiomes, Ores, Trees, and Tweaks Release: WTF-Expedition_1.10.2_v1.3.6.jar

This issue causes a game crash. Which was discovered when testing the features for the latest release of "Enhanced Visuals". Basically I was blowing myself up to see how it responded.

It wasn't a consistent issue, presenting about 3 out of 10 times. However being in close proximity(2-3 blocks) to an explosion, both Creeper and TNT, would result in "Internal Server Shutting Down" and the client closing.

I created a clean instance to test further and the issue didn't persist. I went back into my initial package and disabled the explosion tweaks in WTF and the problem went away in the pack as well.

Additionally, interaction between the two mods makes Enhanced Visuals explosion effects extreme. Bleaching out the screen entirely, that doesn't seem to go away until dunking it water, and incredibly loud 'beep'. 

I'm going to assume that because both mods seem to use a formula, this some how causes explosions to behave oddly. 

A work around to let your users know about is to disable the explosion tweak in the WTF mod.

**Comment by WhiskyTangoFawks** [comment]
This is an incompatibility that I can't do anything on my end to fix, if you want to use enhanced visuals, I recommend turning off custom explosions.  The way my explosions work, is it spreads the computation for the explosion out over several ticks to reduce lag, instead of instantaneously, and enhanced visuals doesn't know how to deal with that, hence it's issues.

**Comment by XvSkItZvX** [comment]
Fair enough, I wasn't able to pinpoint the issue so I posted to both mods. I did disable the explosion tweaks but they were freaking sweet while they lasted lol...

**Comment by WhiskyTangoFawks** [comment]
Go ahead and link the issues, in case the other mod author wants to contact me.  There are probably a few simple things they could do to make them compatible.

**Comment by CreativeMD** [comment]
Actually this is just an issue of EnhancedVisuals. In order to make the beep effect really cool, all other sounds have to be muted by a certain amount. Unfortunately there is a thread issue, which can occur. The more explosion the more likely it will happen.

But i think i found a way to fix it, could try out this version and see if it's fixed?
https://www.dropbox.com/s/ehz39pkvrfwsucy/EnhancedVisuals%20v1.0.10%20mc1.9-1.10.jar?dl=1

**Comment by XvSkItZvX** [comment]
I went ahead and posted results with the new version in the Enhanced Visuals Thread
https://github.com/CreativeMD/EnhancedVisuals/issues/10
